Vagrant.configure(2) do |config|

  # Use Ubuntu 15.04
  config.vm.box = "ubuntu/vivid64"

  # Jenkins
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  # Docker
  config.vm.network "forwarded_port", guest: 2375, host: 2375

  # JBoss
  config.vm.network "forwarded_port", guest: 8081, host: 8081

  # JBoss Admin Port
  config.vm.network "forwarded_port", guest: 9990, host: 9990

  # JBoss Debug Port
  config.vm.network "forwarded_port", guest: 8787, host: 8787

  # Postgres
  config.vm.network "forwarded_port", guest: 5432, host: 5432

  #Enable to change ssh to another port.
  config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
  config.vm.network :forwarded_port, guest: 22, host: 64675, auto_correct: true

  # Share the Git repository with the VM
  config.vm.synced_folder "../", "/yatol"
  config.vm.synced_folder "~/.vagrant.d", "/home/vagrant/.vagrant.d"

  # Configure more memory and cores
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 4
  end

  # Configure provisioning
  config.vm.provision "shell", path: "vagrant_provision.sh"

end
