Vagrant.configure(2) do |config|

  # Use Ubuntu 15.04
  config.vm.box = "ubuntu/vivid64"

  # Forward Jenkins port to host 8080
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  # Share the Git repository with the VM
  config.vm.synced_folder "../", "/yatol"

  # Configure more memory and cores
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 4
  end

  # Configure provisioning
  config.vm.provision "shell", path: "vagrant_provision.sh"

end
